name: 'On Called for Deploying SWA to Azure'

on:
  workflow_call:
    inputs:
      artifact_name_app:
        type: string
        required: false
        description: Artifact name for app
        default: 'app'
      artifact_name_api:
        type: string
        required: false
        description: Artifact name for API
        default: 'api'

env:
  AZURE_RESOURCE_GROUP_NAME: 'rg-${{ secrets.AZURE_ENV_NAME }}'

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_STTAPP_NAME: 'sttapp-${{ secrets.AZURE_ENV_NAME }}'

    steps:
    - name: Download Function app artifact
      uses: actions/download-artifact@v3
      with:
        path: ${{ github.workspace }}/published

    - name: Login to Azure
      uses: Azure/login@v1
      with:
        # creds: ${{ secrets.AZURE_CREDENTIALS }}
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Get SWA token
      shell: bash
      run: |
        swa_token=$(az staticwebapp secrets list -g $AZURE_RESOURCE_GROUP_NAME -n $AZURE_STTAPP_NAME --query "properties.apiKey" -o tsv)

        echo "::add-mask::$swa_token"
        echo "SWA_TOKEN=$swa_token" >> $GITHUB_ENV

    # - name: Deploy SWA to Azure
    #   shell: bash
    #   run: |
    #     swa deploy \
    #         -d ${{ env.SWA_TOKEN }} \
    #         -a ${{ github.workspace }}/published/${{ inputs.artifact_name_app }}/wwwroot \
    #         -i ${{ github.workspace }}/published/${{ inputs.artifact_name_api }} \
    #         --env default

    - name: Deploy SWA to Azure
      uses: Azure/static-web-apps-deploy@v1
      with:
        azure_static_web_apps_api_token: ${{ env.SWA_TOKEN }}
        repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
        action: "upload"
        skip_app_build: true
        ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
        # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
        app_location: "${{ github.workspace }}/published/${{ inputs.artifact_name_app }}/wwwroot" # App source code path
        api_location: "${{ github.workspace }}/published/${{ inputs.artifact_name_api }}" # Api source code path - optional
        output_location: "" # Built app content directory - optional
        ###### End of Repository/Build Configurations ######

    - name: Update app settings on SWA
      shell: bash
      run: |
        appsettings=$(az staticwebapp appsettings set \
          -g $AZURE_RESOURCE_GROUP_NAME \
          -n $AZURE_STTAPP_NAME \
          --setting-names MsGraph__TenantId="${{ secrets.GRAPH_TENANT_ID }}" \
                          MsGraph__ClientId="${{ secrets.GRAPH_CLIENT_ID }}" \
                          MsGraph__ClientSecret="${{ secrets.GRAPH_CLIENT_SECRET }}")
